# Generated by Django 6.0.5 on 2026-07-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_stock_category_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='External image URL (auto-filled from FMP news feed)'),
        ),
    ]
