# Generated by Django 6.0.5 on 2026-08-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_add_news_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_portfolio_growth',
            field=models.BooleanField(default=False, help_text="Show the Portfolio Growth Target section on the user's portfolio page"),
        ),
    ]
